### ISSUE TITLE
ms_graph_state.jsonc file is missing

### ISSUE THREAD

**Issue by vikrant-1188** [areed1192/ms-graph-python-client#4]
ms_graph_state.jsonc file is missing

**Comment by areed1192** [comment]
That's because it's auto generated. If you run one of the example scripts it will walk you through the oAuth process. This assumes you have an app registered in Azure.

**Comment by AnishDe12020** [comment]
Had the same issues, the config file is names "configs" but in the code it is referred to as "config". Change that and this error should be gone

**Comment by AnishDe12020** [comment]
I have opened a PR fixing the issue
