### ISSUE TITLE
So I got an error which terminated my code but the login was successful

### ISSUE THREAD

**Issue by AnishDe12020** [areed1192/ms-graph-python-client#5]
![image](https://user-images.githubusercontent.com/63192115/119480757-9b552480-bd6f-11eb-9859-795963e8df7f.png)
So the login was successful and the jsonc file was successfully creates but I was greeted by the above error. I am using the library by locally installing it using `pip3 install .`. 

Code - https://gist.github.com/AnishDe12020/eebb22369899e0f41ffebe8beb710337
I was trying to make the application after seeing your guide in YouTube

**Comment by AnishDe12020** [comment]
Update: Also happens when I run `use_client.py` from the sample codes. 
![image](https://user-images.githubusercontent.com/63192115/119483389-8a59e280-bd72-11eb-9372-b36b7a1b1c57.png)

**Comment by areed1192** [comment]
It was a bug with the log folder. I forget to add a portion in there to create the folder if it doesn't exist. Pull the latest changes and you should be good.

**Comment by AnishDe12020** [comment]
Thanks for the reply and fix 👍
